---
title: "Project1: Exploring Variances of the Exponential Distribution"
author: "ww44ss"
date: "October 2014"
output: 
html_document:
    keep_md: true
---

##Synopsis

```{r "creatematrix", echo=TRUE}

##create data for analysis

        ##Set seed to make results reproducible
        set.seed(54321)

        ##makes sample sizes variable
        rowsofsamples <- 40
        columnsofdistributions <- 1000

        ##create data frame
        rdata <- replicate(columnsofdistributions, rexp(rowsofsamples, .2)) 
       
        ##look at structure of data
        str(rdata)

```


```{r "historgram_of_means"}

##Take means of columns and plot histrogram with mean and theoretical mean 
        
        ##Compute Column means
        expmeans <- colMeans(rdata)

        ##Generate Historgram
        hist(expmeans, density=20, angle=45, xlim=c(1,9), ylim=c(0,270))

        ##Calculate "Mean of Means"
        meanofdistmeans<-mean(expmeans)
        
        ##Draw lines at mean and theoretical mean = 5
        abline(v=meanofdistmeans, lwd=3, col="red")
        abline(v=5, lwd=3, col="blue")

        ##Label graph
        text(meanofdistmeans,265, "Data Mean", col="red", adj=c(1.1,0))
        text(5,265, "Theoretical Mean", col="blue", adj=c(-.10,0))
```


```{r "variance"}

varofdistmeans = var(expmeans)

print(varofdistmeans)





```
